# Generated by Django 4.0.1 on 2022-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail4u', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=200),
        ),
    ]
